export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_ERROR = 'FETCH_PRODUCT_ERROR';

export const ADD_PRODUCT_TO_USER = 'ADD_PRODUCT_TO_USER';
export const ADD_PRODUCT_TO_USER_SUCCESS = 'ADD_PRODUCT_TO_USER_SUCCESS';
export const ADD_PRODUCT_TO_USER_ERROR = 'ADD_PRODUCT_TO_USER_ERROR';