export const SET_USER_CREDENTIALS = 'SET_USER_CREDENTIALS';

export const SIGNUP_CHANGE = 'SIGNUP_CHANGE';
export const SIGNUP_SAVE = 'SIGNUP_SAVE';
export const SIGNUP_SAVE_SUCCESS = 'SIGNUP_SAVE_SUCCESS';
export const SIGNUP_SAVE_ERROR = 'SIGNUP_SAVE_ERROR';

export const LOGIN_CHANGE = 'LOGIN_CHANGE';
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT = 'LOGOUT';

export const FETCH_PROFILE = 'FETCH_PROFILE';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_ERROR = 'FETCH_PROFILE_ERROR';


export const EDIT_USER_CHANGE = 'EDIT_USER_CHANGE';
export const EDIT_USER = 'EDIT_USER';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_ERROR = 'EDIT_USER_SAVE_ERROR';

export const ADD_OR_REMOVE_PRODUCT_TO_USER = 'ADD_OR_REMOVE_PRODUCT_TO_USER';
export const ADD_OR_REMOVE_PRODUCT_TO_USER_SUCCESS = 'ADD_OR_REMOVE_PRODUCT_TO_USER_SUCCESS';
export const ADD_OR_REMOVE_PRODUCT_TO_USER_ERROR = 'ADD_OR_REMOVE_PRODUCT_TO_USER_ERROR';

export const FETCH_USER_PRODUCTS = 'FETCH_USER_PRODUCTS';
export const FETCH_USER_PRODUCTS_SUCCESS = 'FETCH_USER_PRODUCTS_SUCCESS';
export const FETCH_USER_PRODUCTS_ERROR = 'FETCH_USER_PRODUCTS_ERROR';